from core.libs.generic_state import GenericState

class UpdaterState(GenericState):
    UPDATER_STATE_IDLE = "IDLE"
    UPDATER_STATE_NO_UPDATE_REQUIRED = "NO_UPDATE_REQUIRED"
    UPDATER_STATE_CHECKING = "CHECKING"
    UPDATER_STATE_UPDATE_AVAILABLE = "UPDATE_AVAILABLE"
    UPDATER_STATE_DOWNLOADING = "DOWNLOADING"
    UPDATER_STATE_READY_FOR_INSTALL = "READY_FOR_INSTALL"
    UPDATER_STATE_INSTALLING = "INSTALLING"
    UPDATER_STATE_UPDATE_SUCCEEDED = "UPDATE_SUCCEEDED"
    UPDATER_STATE_UPDATE_FAILED = "UPDATE_FAILED"
    _DEFAULT = UPDATER_STATE_IDLE
